services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: books
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SSL: 'false'
      # container tự động khởi tạo lại khi có sự cố
      # restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - db_app:/var/lib/mysql
  splash:
    image: scrapinghub/splash
    container_name: splash
    ports:
      - "8050:8050"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"

volumes:
  db_app:
  redis: